[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
remappings = [  
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
celo-sepolia = "https://forno.celo-sepolia.celo-testnet.org/"
celo = "https://forno.celo.org"
base-sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
celo-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
celo = { key = "${ETHERSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }